/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author GPC
 */
public class Frame extends javax.swing.JFrame implements KeyListener {

    public double ANS;

    /**
     * Creates new form Frame
     */
    public Frame() {
        super();
        initComponents();
        ANS = 0;
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisplay = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelDisplay = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonDPoint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAns = new javax.swing.JButton();
        jButtonPow = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Calculator");
        setBackground(java.awt.Color.darkGray);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(455, 400));

        jPanelDisplay.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDisplay.setForeground(java.awt.Color.darkGray);

        jDesktopPane1.setBackground(new java.awt.Color(102, 153, 0));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDisplay.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelDisplay.setForeground(new java.awt.Color(0, 51, 51));
        jLabelDisplay.setText("3.14568");

        jDesktopPane1.setLayer(jLabelDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDisplayLayout = new javax.swing.GroupLayout(jPanelDisplay);
        jPanelDisplay.setLayout(jPanelDisplayLayout);
        jPanelDisplayLayout.setHorizontalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanelDisplayLayout.setVerticalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelButtons.setBackground(new java.awt.Color(51, 51, 51));
        jPanelButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelButtons.setForeground(java.awt.Color.darkGray);

        jButton0.setBackground(new java.awt.Color(102, 102, 102));
        jButton0.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDPoint.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDPoint.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDPoint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDPoint.setText(".");
        jButtonDPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDPointActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonAns.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAns.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAns.setText("Ans");
        jButtonAns.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnsActionPerformed(evt);
            }
        });

        jButtonPow.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPow.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPow.setText("^");
        jButtonPow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPowActionPerformed(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlus.setText("+");
        jButtonPlus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonEq.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEq.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonEq.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEq.setText("=");
        jButtonEq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqActionPerformed(evt);
            }
        });

        jButtonMinus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMinus.setText("-");
        jButtonMinus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonDivision.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDivision.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDivision.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivision.setText("÷");
        jButtonDivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonMult.setBackground(new java.awt.Color(102, 102, 102));
        jButtonMult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonMult.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMult.setText("×");
        jButtonMult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 102, 0));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("CLEAR");
        jButtonClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonDel.setBackground(new java.awt.Color(255, 102, 0));
        jButtonDel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDel.setText("DEL");
        jButtonDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jButtonDPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jButtonPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPowActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...") {
            jLabelDisplay.setText(jLabelDisplay.getText() + "^");
        }

    }//GEN-LAST:event_jButtonPowActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabelDisplay.setText(jLabelDisplay.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqActionPerformed
        // TODO add your handling code here:
        String input = jLabelDisplay.getText();
        double result = 0;
        ArrayList<Double> nums = new ArrayList<>();
        ArrayList<String> operators = new ArrayList<>();
        String temp = "";
        char lastChar = 'c', currentChar = 'c';
        String lastCharType = "empty", currentCharType = "empty";
        String allOperators = "+-×÷^";
        System.out.println("===========Start of Parsing===========");
        for (int i = 0; i < input.length(); i++) {
            currentChar = input.charAt(i);
            System.out.println("Character  " + (i + 1) + ": " + currentChar);
            try {
                try {
                    Integer.parseInt(Character.toString(currentChar));
                    temp += currentChar;
                    lastCharType = "number";
                    lastChar = currentChar;
                    System.out.println("It's the number " + currentChar);
                } catch (NumberFormatException e) {
                    if (currentChar == '-' && temp == "") {
                        currentCharType = "minus";
                    } else if (allOperators.contains(Character.toString(currentChar))) {
                        currentCharType = "operator";
                    } else if (currentChar == '.') {
                        currentCharType = "decimalPoint";
                    } else {
                        currentCharType = "unknown";
                    }
                    System.out.println("Not a number! It's a " + currentCharType + "(" + currentChar + ")");

                    switch (currentCharType) {
                        case "minus" -> {
                            if (temp != "") {
                                System.out.println("minus in the middle of number");
                                throw new MyException();
                            } else if (temp == "") {
                                temp += currentChar;
                                lastCharType = "minus";
                                lastChar = currentChar;
                            } else {
                                throw new MyException();
                            }
                        }
                        case "decimalPoint" -> {
                            if (temp.contains(".")) {
                                System.out.println("multiple decimal points thrown");
                                throw new MyException();
                            } else {
                                temp += ".";
                                lastCharType = "decimalPoint";
                                lastChar = '.';
                            }
                        }
                        case "operator" -> {
                            if (allOperators.contains(Character.toString(lastChar))) {
                                System.out.println("multiple operators");
                                throw new MyException();

                            }
                            nums.add(Double.parseDouble(temp));
                            System.out.println("Added " + temp + " to nums!");
                            temp = "";
                            operators.add(Character.toString(currentChar));
                            System.out.println("Added " + currentChar + " to operators!");
                            lastCharType = "operator";
                            lastChar = currentChar;
                        }
                        case "unknown" -> {
                            System.out.println("unkown thrown");
                            throw new MyException();
                        }
                    }

                }
            } catch (MyException e) {
                jLabelDisplay.setText("Err...");
                break;
            }

        }
        if (temp != "") {
            nums.add(Double.parseDouble(temp));
            System.out.println("Added " + temp + " to nums!");
        }
        if (allOperators.contains(Character.toString(lastChar))) {
            jLabelDisplay.setText("Err...");
        }
        System.out.println("===========End of Parsing===========");

        for (double n : nums) {
            System.out.println("Nums entry: " + n);
        }
        for (String c : operators) {
            System.out.println("Operator entry:" + c);
        }

        if (nums.size() == 1 && jLabelDisplay.getText() != "Err...") {
            result = nums.get(0);
            ANS = result;
        } else if (jLabelDisplay.getText() != "Err..." && nums.size() != 1) {

            while (true) {
                if (operators.indexOf("^") != -1) {
                    int index = operators.indexOf("^");
                    nums.set(index, Math.pow(nums.get(index).doubleValue(), nums.get(index + 1).doubleValue()));
                    nums.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("×") != -1) {
                    int index = operators.indexOf("×");
                    nums.set(index, nums.get(index).doubleValue() * nums.get(index + 1).doubleValue());
                    nums.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("÷") != -1) {
                    int index = operators.indexOf("÷");
                    nums.set(index, nums.get(index).doubleValue() / nums.get(index + 1).doubleValue());
                    nums.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("+") != -1) {
                    int index = operators.indexOf("+");
                    nums.set(index, nums.get(index).doubleValue() + nums.get(index + 1).doubleValue());
                    nums.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("-") != -1) {
                    int index = operators.indexOf("-");
                    nums.set(index, nums.get(index).doubleValue() - nums.get(index + 1).doubleValue());
                    nums.remove((int) (index + 1));
                    operators.remove((int) index);
                } else {
                    break;
                }
            }
            result = nums.get(0);
            ANS = result;
            String strResult = String.format("%.3f", result);
            jLabelDisplay.setText(strResult);
        }
    }//GEN-LAST:event_jButtonEqActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "-");
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "÷");
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jLabelDisplay.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnsActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...") {
            jLabelDisplay.setText(String.format("%.3f", ANS));
        }

    }//GEN-LAST:event_jButtonAnsActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        String temp = jLabelDisplay.getText();
        if (temp.length() > 0) {
            if (temp != "Err...") {
                temp = temp.substring(0, temp.length() - 1);
                jLabelDisplay.setText(temp);
            }
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonDPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDPointActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + ".");
    }//GEN-LAST:event_jButtonDPointActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...")
            jLabelDisplay.setText(jLabelDisplay.getText() + "+");
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        // TODO add your handling code here:
        if (jLabelDisplay.getText() != "Err...") {
            jLabelDisplay.setText(jLabelDisplay.getText() + "×");
        }

    }//GEN-LAST:event_jButtonMultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAns;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDPoint;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPow;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDisplay;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println(e.getKeyChar() + " pressed.");
        int key = e.getKeyCode();
        switch (key) {
            case KeyEvent.VK_NUMPAD0 ->
                this.jButton0ActionPerformed(null);
            case KeyEvent.VK_NUMPAD1 ->
                this.jButton1ActionPerformed(null);
            case KeyEvent.VK_NUMPAD2 ->
                this.jButton2ActionPerformed(null);
            case KeyEvent.VK_NUMPAD3 ->
                this.jButton3ActionPerformed(null);
            case KeyEvent.VK_NUMPAD4 ->
                this.jButton4ActionPerformed(null);
            case KeyEvent.VK_NUMPAD5 ->
                this.jButton5ActionPerformed(null);
            case KeyEvent.VK_NUMPAD6 ->
                this.jButton6ActionPerformed(null);
            case KeyEvent.VK_NUMPAD7 ->
                this.jButton7ActionPerformed(null);
            case KeyEvent.VK_NUMPAD8 ->
                this.jButton8ActionPerformed(null);
            case KeyEvent.VK_NUMPAD9 ->
                this.jButton9ActionPerformed(null);
            case 106/*mult*/ ->
                this.jButtonMultActionPerformed(null);
            case 107/*plus*/ ->
                this.jButtonPlusActionPerformed(null);
            case 109/*minus*/ ->
                this.jButtonMinusActionPerformed(null);
            case 110/*point*/ ->
                this.jButtonDPointActionPerformed(null);
            case 111/*divide*/ ->
                this.jButtonDivisionActionPerformed(null);
            case 10/*enter*/ ->
                this.jButtonEqActionPerformed(null);
            case 8/*backspace*/ ->
                this.jButtonDelActionPerformed(null);
            case 27/*escape*/ ->
                this.jButtonClearActionPerformed(null);
            case 54/*power*/ ->
                this.jButtonPowActionPerformed(null);
        }

    }

    @Override
    public void keyReleased(KeyEvent e) {
        System.out.println(e.getKeyCode() + " released.");

    }
}
