/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author GPC
 */
public class Frame extends javax.swing.JFrame implements KeyListener {

    public double ANS;
    public static final String allOperators = "+-×÷^";
    public static int status = 101;
    //101: all good
    //401: general/unknown error
    //402: operator at start, multiple decimal points, unclosed bracket, minus in the middle of number

    /**
     * Creates new form Frame
     */
    public Frame() {
        super();
        initComponents();
        ANS = 0;
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisplay = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelDisplay = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonDPoint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonAns = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonPow = new javax.swing.JButton();
        jPanelStatus = new javax.swing.JPanel();
        jButtonStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Calculator");
        setBackground(java.awt.Color.darkGray);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setForeground(java.awt.Color.darkGray);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(455, 400));

        jPanelDisplay.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDisplay.setForeground(java.awt.Color.darkGray);
        jPanelDisplay.setFocusable(false);

        jDesktopPane1.setBackground(new java.awt.Color(102, 153, 0));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.setFocusable(false);

        jLabelDisplay.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelDisplay.setForeground(new java.awt.Color(0, 51, 51));
        jLabelDisplay.setText("3.14568");
        jLabelDisplay.setFocusable(false);

        jDesktopPane1.setLayer(jLabelDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDisplayLayout = new javax.swing.GroupLayout(jPanelDisplay);
        jPanelDisplay.setLayout(jPanelDisplayLayout);
        jPanelDisplayLayout.setHorizontalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanelDisplayLayout.setVerticalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelButtons.setBackground(new java.awt.Color(51, 51, 51));
        jPanelButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelButtons.setForeground(java.awt.Color.darkGray);
        jPanelButtons.setFocusable(false);

        jButton0.setBackground(new java.awt.Color(102, 102, 102));
        jButton0.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton0.setFocusable(false);
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDPoint.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDPoint.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDPoint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDPoint.setText(".");
        jButtonDPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDPoint.setFocusable(false);
        jButtonDPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDPointActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonAns.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonAns.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAns.setText("Ans");
        jButtonAns.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAns.setFocusable(false);
        jButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnsActionPerformed(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlus.setText("+");
        jButtonPlus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPlus.setFocusable(false);
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonEq.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEq.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonEq.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEq.setText("=");
        jButtonEq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEq.setFocusable(false);
        jButtonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqActionPerformed(evt);
            }
        });

        jButtonMinus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMinus.setText("-");
        jButtonMinus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMinus.setFocusable(false);
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonDivision.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDivision.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDivision.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivision.setText("÷");
        jButtonDivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDivision.setFocusable(false);
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonMult.setBackground(new java.awt.Color(102, 102, 102));
        jButtonMult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonMult.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMult.setText("×");
        jButtonMult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMult.setFocusable(false);
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 102, 0));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("CLEAR");
        jButtonClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonClear.setFocusable(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonDel.setBackground(new java.awt.Color(255, 102, 0));
        jButtonDel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDel.setText("DEL");
        jButtonDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDel.setFocusable(false);
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButtonPow.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPow.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPow.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPow.setText("^");
        jButtonPow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPow.setFocusable(false);
        jButtonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanelButtonsLayout.createSequentialGroup()
                        .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                    .addGroup(jPanelButtonsLayout.createSequentialGroup()
                        .addComponent(jButtonDPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelStatus.setBackground(new java.awt.Color(51, 51, 51));
        jPanelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N

        jButtonStatus.setBackground(new java.awt.Color(102, 102, 102));
        jButtonStatus.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jButtonStatus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStatus.setText("<html><p align=\"left\">Status: All good!</p></html>");
        jButtonStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonStatus.setFocusable(false);
        jButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        String temp = jLabelDisplay.getText();
        if (!temp.isEmpty()) {
            setStatus(101, "Status: waiting...");
            temp = temp.substring(0, temp.length() - 1);
            jLabelDisplay.setText(temp);
        }

    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jLabelDisplay.setText("");
        setStatus(101, "Status: all good!");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        // TODO add your handling code here:
        appendDisplayWithOperator('×');
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
        appendDisplayWithOperator('÷');
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        appendDisplayWithOperator('-');
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqActionPerformed
        double result;
        String input = jLabelDisplay.getText();
        if (input.isBlank()) {
            jLabelDisplay.setText(String.valueOf(ANS));
        } else {
            //displaying the result
            result = resultOfExpression(input);
            ANS = result;
            String strResult; // = String.format("%.3f", result);
            if (status == 101) {

                if ((int) result == result) {
                    strResult = String.valueOf((int) result);
                } else {
                    strResult = String.format("%.3f", result);
                }
                if (status == 101) {
                    jLabelDisplay.setText(strResult);
                }
            }
        }
    }//GEN-LAST:event_jButtonEqActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        if (status == 101) 
        jLabelDisplay.setText(jLabelDisplay.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        appendDisplayWithOperator('+');
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPowActionPerformed
        // TODO add your handling code here:
        appendDisplayWithOperator('^');
    }//GEN-LAST:event_jButtonPowActionPerformed

    private void jButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnsActionPerformed
        // TODO add your handling code here:
        String strResult;
        if (status == 101) {
            if ((int) ANS == ANS) {
                strResult = String.valueOf((int) ANS);
            } else {
                strResult = String.format("%.3f", ANS);
            }

            jLabelDisplay.setText(strResult);
        }
    }//GEN-LAST:event_jButtonAnsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDPointActionPerformed
        // TODO add your handling code here:
        if (!jLabelDisplay.getText().isEmpty()) {
            ArrayList<Double> numbers = new ArrayList<Double>();
            ArrayList<String> operators = new ArrayList<String>();
            expressionToArrays(jLabelDisplay.getText(), numbers, operators);
            if (!numbers.isEmpty()) {
                double lastNum = numbers.get(numbers.size() - 1);
                if ((int) lastNum != lastNum) {
                    setStatus(101, "already placed decimal point");
                } else {
                    jLabelDisplay.setText(jLabelDisplay.getText() + ".");
                }
            }
    }//GEN-LAST:event_jButtonDPointActionPerformed
        else
            jLabelDisplay.setText(jLabelDisplay.getText() + ".");

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
//        if (status == 101)
        jLabelDisplay.setText(jLabelDisplay.getText() + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStatusActionPerformed

    //if the last character on display is already an operator then it's replaced
    private void appendDisplayWithOperator(char c) {
        if (status == 101 && !jLabelDisplay.getText().isEmpty() && !(this.getLastChar() == '-' && jLabelDisplay.getText().length() == 1)) {
            if (!"+-×÷^.".contains(Character.toString(jLabelDisplay.getText().charAt(jLabelDisplay.getText().length() - 1)))) {
                jLabelDisplay.setText(jLabelDisplay.getText() + c);
            } else {
                jLabelDisplay.setText(jLabelDisplay.getText().substring(0, jLabelDisplay.getText().length() - 1) + c);
            }

        } else if (status != 101); else {
            if (c == '-') {
                jLabelDisplay.setText("-");
            } else {
                if (status == 101) {
                    jLabelDisplay.setText("");
                }
            }
        }

    }

    private char getLastChar() {
        if (!jLabelDisplay.getText().isEmpty()) {
            char lastChar = jLabelDisplay.getText().charAt(jLabelDisplay.getText().length() - 1);
            return lastChar;
        } else {
            return 'e';
        }
    }

    private String getLastCharString() {
        if (!jLabelDisplay.getText().isEmpty()) {
            String lastChar = Character.toString(jLabelDisplay.getText().charAt(jLabelDisplay.getText().length() - 1));
            return lastChar;
        } else {
            return "e";
        }
    }

    //set status
    private void setStatus(int n, String message) {
        Frame.status = n;
        setStatusMessage(n, message);
    }

    private void setStatusMessage(int n, String message) {
        switch (n) {
            case 401: {
                jButtonStatus.setText("Error: " + message);
                break;
            }
            case 101: {
                jButtonStatus.setText(message);
                break;
            }
        }
        jButtonStatus.doClick();

    }

    //TODO: return the last number in the display
    private String getLastNumberString() {
        return "TODO";
    }

    //string of numbers and operators to ArrayLists
    private void expressionToArrays(String input, ArrayList<Double> numbers, ArrayList<String> operators) {
        String temp = ""; //buffer for numbers before adding to the numbers array
        char lastChar = 'c', currentChar = 'c';
        String lastCharType = "empty", currentCharType = "empty";

        //parsing starts here
        System.out.println("===========Start of Parsing===========");
        for (int i = 0; i < input.length(); i++) {
            currentChar = input.charAt(i);
            System.out.println("Character  " + (i + 1) + ": " + currentChar);
            try {
                try {
                    Integer.parseInt(Character.toString(currentChar));
                    temp += currentChar;
                    lastCharType = "number";
                    lastChar = currentChar;
                    System.out.println("It's the number " + currentChar);
                } catch (NumberFormatException e) {
                    if (currentChar == '-' && temp == "") {
                        currentCharType = "minus";
                    } else if (allOperators.contains(Character.toString(currentChar))) {
                        currentCharType = "operator";
                    } else if (currentChar == '.') {
                        currentCharType = "decimalPoint";
                    } else {
                        currentCharType = "unknown";
                    }
                    System.out.println("It's the " + currentCharType + " " + currentChar);

                    switch (currentCharType) {
                        case "minus" -> {
                            if (temp != "") {
                                System.out.println("minus in the middle of number");
                                throw new MyException();
                            } else if (temp == "") {
                                temp += currentChar;
                                lastCharType = "minus";
                                lastChar = currentChar;
                            } else {
                                throw new MyException(401, "unknown error");
                            }
                        }
                        case "decimalPoint" -> {
                            temp += ".";
                            lastCharType = "decimalPoint";
                            lastChar = '.';
                        }
                        case "operator" -> {
                            numbers.add(Double.parseDouble(temp));
                            System.out.println("Added " + temp + " to nums!");
                            temp = "";
                            operators.add(Character.toString(currentChar));
                            System.out.println("Added " + currentChar + " to operators!");
                            lastCharType = "operator";
                            lastChar = currentChar;
                        }
                        case "unknown" -> {
                            System.out.println("unkown thrown");
                            throw new MyException(401, "unknown erorr");
                        }
                    }

                }
            } catch (MyException | NumberFormatException e) {
//                jLabelDisplay.setText("Err...");
                System.out.println(e.getMessage());
                setStatus(401, e.getMessage());
                break;
            }

        }
        if (temp != "") {
            try {
                numbers.add(Double.parseDouble(temp));
                System.out.println("Added " + temp + " to nums!");
                setStatus(101, "Status: all good.");
            } catch (NumberFormatException e) {
                setStatus(401, e.getMessage());
            }
        }
        if (allOperators.contains(Character.toString(lastChar))) {
            setStatus(401, "");
        }
        System.out.println("===========End of Parsing===========");
        //parsing ends

    }

    //result of applying an array of operators to an array of numbers
    private double resultOfArrays(ArrayList<Double> numbers, ArrayList<String> operators) {
        if (numbers.size() != operators.size() + 1) {
            setStatus(401, "Error: ending with operator");
            return 0;
        }
        if (numbers.size() == 1 && status == 101) {
            ANS = numbers.get(0);
            return numbers.get(0);
        } else if (status == 101 && numbers.size() != 1) {

            while (true) {
                if (operators.indexOf("^") != -1) {
                    int index = operators.indexOf("^");
                    numbers.set(index, Math.pow(numbers.get(index).doubleValue(), numbers.get(index + 1).doubleValue()));
                    numbers.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("×") != -1) {
                    int index = operators.indexOf("×");
                    numbers.set(index, numbers.get(index).doubleValue() * numbers.get(index + 1).doubleValue());
                    numbers.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("÷") != -1) {
                    int index = operators.indexOf("÷");
                    numbers.set(index, numbers.get(index).doubleValue() / numbers.get(index + 1).doubleValue());
                    numbers.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("+") != -1) {
                    int index = operators.indexOf("+");
                    numbers.set(index, numbers.get(index).doubleValue() + numbers.get(index + 1).doubleValue());
                    numbers.remove((int) (index + 1));
                    operators.remove((int) index);
                } else if (operators.indexOf("-") != -1) {
                    int index = operators.indexOf("-");
                    numbers.set(index, numbers.get(index).doubleValue() - numbers.get(index + 1).doubleValue());
                    numbers.remove((int) (index + 1));
                    operators.remove((int) index);
                } else {
                    break;
                }
            }

            ANS = numbers.get(0);
            return numbers.get(0);
        }
        return 0;
    }

    //get double result from a string of only numbers and operators
    private double resultOfExpression(String input) {
        input = jLabelDisplay.getText();
        if (!input.isEmpty()) {
            ArrayList<Double> numbers = new ArrayList<>();
            ArrayList<String> operators = new ArrayList<>();
            //string split into numbers and operators in ArrayLists in order of appearance
            expressionToArrays(input, numbers, operators);
            //logging the numsbers and operators arrays
            for (double n : numbers) {
                System.out.println("Nums entry: " + n);
            }
            for (String c : operators) {
                System.out.println("Operator entry:" + c);
            }

            //calculating the result using the numbers and the operators arrays
            return resultOfArrays(numbers, operators);
        }
        return 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAns;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDPoint;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPow;
    private javax.swing.JButton jButtonStatus;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDisplay;
    private javax.swing.JPanel jPanelStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println(e.getKeyChar() + " (" + e.getKeyCode() + ") pressed.");
        setStatus(101, "Status: waiting...");
        int key = e.getKeyCode();
        switch (key) {
            case KeyEvent.VK_NUMPAD0 ->
                this.jButton0.doClick();
            case KeyEvent.VK_NUMPAD1 ->
                this.jButton1.doClick();
            case KeyEvent.VK_NUMPAD2 ->
                this.jButton2.doClick();
            case KeyEvent.VK_NUMPAD3 ->
                this.jButton3.doClick();
            case KeyEvent.VK_NUMPAD4 ->
                this.jButton4.doClick();
            case KeyEvent.VK_NUMPAD5 ->
                this.jButton5.doClick();
            case KeyEvent.VK_NUMPAD6 ->
                this.jButton6.doClick();
            case KeyEvent.VK_NUMPAD7 ->
                this.jButton7.doClick();
            case KeyEvent.VK_NUMPAD8 ->
                this.jButton8.doClick();
            case KeyEvent.VK_NUMPAD9 ->
                this.jButton9.doClick();
            case 106/*mult*/ ->
                this.jButtonMult.doClick();
            case 107/*plus*/ ->
                this.jButtonPlus.doClick();
            case 109/*minus*/ ->
                this.jButtonMinus.doClick();
            case 110/*point*/ ->
                this.jButtonDPoint.doClick();
            case 111/*divide*/ ->
                this.jButtonDivision.doClick();
            case 10/*enter*/ ->
                this.jButtonEq.doClick();
            case 8/*backspace*/ ->
                this.jButtonDel.doClick();
            case 27/*escape*/ ->
                this.jButtonClear.doClick();
            case 54/*power*/ ->
                this.jButtonPow.doClick();
        }

    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
